### ISSUE TITLE
Inaccuracies with peak readings of graphs

### ISSUE THREAD

**Issue by molejado** [henrygd/beszel#157] opened 2024-09-04 12:00 UTC
Hi, thanks for the project.
I encountered a discrepancy in the time value when changing the scale of the graphs. In my case, the peak load is single and I can conclude that the readings are shifted in the peak threshold. The load is created by the scheduler at the same time 03:00, every day (backups).

The 12-hour peak of the graph exactly matches my time.
![chrome_OJnUyTZRCI](https://github.com/user-attachments/assets/6b17c3be-5ebf-41d6-a012-cd19bc2beea9)

The 24-hour peak of the graph shifts by 10 minutes, relative to the 12-hour one
![chrome_eWBwTPS4z4](https://github.com/user-attachments/assets/1affb4a5-41ff-4208-aff2-72e264738ccf)

1 week, the peak of the graph shifts +2 hours forward relative to the 12-hour graph
![chrome_5hVNfTb4He](https://github.com/user-attachments/assets/bf396949-6596-4c1b-9dae-dd5aca508439)

30 day, the peak of the graph shifts +4 hours forward relative to the 12-hour graph
![chrome_JBcxHSHkvt](https://github.com/user-attachments/assets/83dec08d-37fd-44e8-84a6-063bce630a8f)

Perhaps I do not understand the peak points of the graph correctly.

**Comment by henrygd** [comment] 2024-09-04 17:39
Each data point in the chart records the average over the whole time period since the last data point.

- 1 hour chart is 1 minute average
- 12 hour chart is 10 minute average
- 24 hour chart is 20 minute average
- 1 week chart is 2 hour average
- 30 day chart is 8 hour average

The peaks and troughs become more difficult to distinguish in longer charts because they are distributed over more time.

I do want to add peak values in at some point. There is an issue you can reference here: #132.

We may also be able to increase the number of data points in longer charts eventually. I wanted to be conservative to start with.

I will close the issue since this is intended behavior, but let me know if you have further questions.

**Closed by henrygd** 2024-09-04 17:39 UTC
