### ISSUE TITLE
Request: New environment variable BASE_URL

### ISSUE THREAD

**Issue by ARC-XX** [henrygd/beszel#331] opened 2024-12-18 02:46 UTC
For the sake of system integration or connection encryption, please add support for custom BASE_URL, so that we can customize the URL prefix.

Such as BASE_URL=/aaaa-bbbb-cccc-dddd, then tail https://hostname/aaaa-bbbb-cccc-dddd to show dashboard;

**Comment by henrygd** [comment] 2024-12-18 18:32
Duplicate of #33 

I will try to add support for this in the next couple of releases

**Closed by henrygd** 2024-12-18 18:32 UTC
