### ISSUE TITLE
Windows Agent with Malware??

### ISSUE THREAD

**Issue by Pootch** [henrygd/beszel#46] opened 2024-07-27 15:25 UTC
https://www.virustotal.com/gui/file/064157849a98cbedce128f3ff5ad2c1fb78ee6af2f4ec093bf68e96259b0e9c1/detection

Windows Defender reportet malware and so virustotal.com.

**Comment by Pootch** [comment] 2024-07-27 15:29
Trojan.WinGo.Merlin

**Comment by henrygd** [comment] 2024-07-27 16:55
This is an open source library. You can read the code for yourself and I encourage anyone to audit and help improve it. I think the agent is only around 400 lines.

The external libraries it uses -- [gopsutil](https://github.com/shirou/gopsutil) and [gliderlabs/ssh](https://github.com/gliderlabs/ssh) -- are widely used and trusted.

The executables are built automatically through GitHub actions, but if this is a concern it's easy to clone the repo and compile for yourself.

It's not surprising to me that Windows Defender would flag the agent, considering it's an exe from an unknown publisher trying to run an SSH server and collect system metrics. Without background context that does seem suspicious.

As far as virustotal.com - only 1 out of 75 vendors detecting a trojan is a good indication that it's a false positive, no? From a quick look, there's not much to go on as to why it was actually flagged.

Please see #18 for more information on the Windows files. I haven't tested them myself and didn't plan to release them until I did. But others here and on reddit asked to test them. I'll remove them from the last release, but you can upload them file to your post in case anyone else wants to have a look.

**Comment by henrygd** [comment] 2024-07-27 16:58
> not just windows. After deploying it my ubuntu VM was compromised within 12h and I had to re-deploy the machine.

I'm sorry that happened to you, but it's very unlikely that it was caused by this program.

Any details you can provide about this, outside of coincidental timing, would be appreciated.

**Comment by henrygd** [comment] 2024-07-27 17:26
Update: I just compiled the [ssh-publickey example](https://github.com/gliderlabs/ssh/blob/master/_examples/ssh-publickey/public_key.go) straight from the [gliderlabs/ssh repo](https://github.com/gliderlabs/ssh) and uploaded it to virustotal.com as a test.

It also got flagged for malware by two vendors. This is known legitimate software. So it seems clear that false positives are common when checking against 75 different vendors with different methodologies.

https://www.virustotal.com/gui/file/346c04fdabfc51c8c111249e04dadb5cf7e07dc1338060c6dbdaa89037647498

I'm going to close this, since the title is a bit sensational and the virustotal.com scan isn't solid evidence of the actual presence of malware.

**Closed by henrygd** 2024-07-27 17:26 UTC

**Comment by Pootch** [comment] 2024-07-29 14:26
Thanks you.
Where can we find the windows agent binaries now? Have they been deleted?

**Comment by henrygd** [comment] 2024-07-29 15:50
@Pootch see https://github.com/henrygd/beszel/discussions/18#discussioncomment-10181420

**Comment by v1rusnl** [comment] 2025-04-28 16:17
Version 0.11 is also flagged by Defender:

`Trojan:Script/Sabsik.FL.A!ml`
