### ISSUE TITLE
Down server notifications repeated.

### ISSUE THREAD

**Issue by cid214** [henrygd/beszel#129] opened 2024-08-22 22:40 UTC
This has happened twice lately, and the same general root cause (agent inaccessible on a server due to network configuration) are present.

I have an OCI instance that I'm monitoring, and in this specific instance, it crashed and came up without the firewall rule that would allow the Beszel server to contact the agent.

When I visited the Beszel server web page, the 'down server' emails triggered, which you'd expect, but in this case it triggered 85 times in immediate succession, which is NOT what I'd expect.

![Screenshot 2024-08-22 173607](https://github.com/user-attachments/assets/de4d0579-8f89-466b-b97a-4f5c798be26c)

I'm using the 0.2 server and agent.

Let me know what other details I can provide that might help in tracking down what the heck caused that to happen since USUALLY the down server notification triggers once like you'd expect, but it appears there's something that can cause it to do that.

**Comment by henrygd** [comment] 2024-08-22 22:57
Thank you! This is a duplicate of #97 but more or less confirms that it's a problem with the application.

Can you please go to the logs page in pocketbase and search for "Sent alert"? Do the multiple events show up there as well?

**Comment by cid214** [comment] 2024-08-22 23:03
I don't see any sent alert notices, but I do see the events that triggered them:

created | 2024-08-22 22:34:05.655 UTC
message | Failed to connect:
data.err | dial tcp 10.x.x.x:45876: i/o timeout
data.port | 45876

There's 85 of those for this instance, and the ~300 for the time it happened previously.

Timestamps are between 2024-08-22 22:34:00.690 UTC and 2024-08-22 22:34:05.655 UTC so just barely under a second for the 85 failures and emails to be generated.

**Comment by henrygd** [comment] 2024-08-22 23:10
Okay thanks, I'll look into it and try to release a patch soon. Obviously you might want to turn off status notifications in the meantime.

**Comment by henrygd** [comment] 2024-08-23 17:04
When you have an opportunity, can you tell me if the message "Existing SSH connection closed. Retrying..." was logged around this time period as well? And if so, if it was logged repeatedly?

Spent some time on this but haven't been able to replicate yet.

**Comment by cid214** [comment] 2024-08-23 17:06
Yep, looks like roughly the same number of those errors as the failed to connect ones/emails about it being down, and the timestamps align perfectly with the previous log ones.

**Comment by roughnecks** [comment] 2024-08-23 17:11
Searched for "existing" and I found the same errors at the same time of notifications..

**Comment by henrygd** [comment] 2024-09-03 22:44
This should be fixed now. Please let me know if it happens again!

**Closed by henrygd** 2024-09-03 22:44 UTC
Labels: bug
